// Mock data for development
export const mockEmployees = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@example.com',
    phone: '+1 (555) 123-4567',
    age: 32,
    class: 'Senior',
    attendance: 98.5,
    subjects: ['JavaScript', 'React', 'GraphQL'],
    department: 'Engineering',
    position: 'Senior Developer',
    joinDate: '2022-03-15',
    address: '123 Main St, Boston, MA',
    bio: 'Sarah is a senior developer with over 8 years of experience in web development. She specializes in frontend technologies and has led several successful projects for the company. Sarah is passionate about creating efficient, user-friendly applications.',
    education: [
      'M.S. Computer Science, MIT, 2018',
      'B.S. Computer Science, Boston University, 2015',
    ],
    skills: ['JavaScript', 'React', 'GraphQL', 'TypeScript', 'Node.js', 'MongoDB'],
    performance: 9.2,
    notes: 'Excellent team player and mentor to junior developers.',
    profileImage: 'https://randomuser.me/api/portraits/women/44.jpg',
  },
  {
    id: '2',
    name: 'David Lee',
    email: 'david.lee@example.com',
    phone: '+1 (555) 234-5678',
    age: 28,
    class: 'Mid-level',
    attendance: 92.8,
    subjects: ['Node.js', 'Express', 'MongoDB'],
    department: 'Engineering',
    position: 'Backend Developer',
    joinDate: '2023-01-20',
    address: '456 Oak St, San Francisco, CA',
    bio: 'David is a backend developer who excels at building scalable API services. He has worked extensively with Node.js and MongoDB. David is currently leading the optimization of our database queries.',
    education: [
      'B.S. Computer Engineering, UC Berkeley, 2020',
    ],
    skills: ['Node.js', 'Express', 'MongoDB', 'REST API', 'Docker', 'AWS'],
    performance: 8.5,
    notes: 'Strong problem-solver with great attention to detail.',
    profileImage: 'https://randomuser.me/api/portraits/men/22.jpg',
  },
  {
    id: '3',
    name: 'Emily Chen',
    email: 'emily.chen@example.com',
    phone: '+1 (555) 345-6789',
    age: 30,
    class: 'Senior',
    attendance: 97.2,
    subjects: ['UI/UX', 'Figma', 'Design Systems'],
    department: 'Design',
    position: 'Senior UI/UX Designer',
    joinDate: '2021-09-10',
    address: '789 Pine St, New York, NY',
    bio: 'Emily is an experienced UI/UX designer with a strong portfolio of web and mobile applications. She has a keen eye for detail and is passionate about creating intuitive user experiences. Emily recently redesigned our main dashboard interface.',
    education: [
      'M.A. Interaction Design, NYU, 2019',
      'B.A. Graphic Design, RISD, 2016',
    ],
    skills: ['UI/UX', 'Figma', 'Adobe XD', 'Sketch', 'Design Systems', 'Prototyping'],
    performance: 9.0,
    notes: 'Excellent collaborator across teams.',
    profileImage: 'https://randomuser.me/api/portraits/women/66.jpg',
  },
  {
    id: '4',
    name: 'Michael Williams',
    email: 'michael.williams@example.com',
    phone: '+1 (555) 456-7890',
    age: 35,
    class: 'Senior',
    attendance: 89.6,
    subjects: ['Project Management', 'Agile', 'Scrum'],
    department: 'Product',
    position: 'Product Manager',
    joinDate: '2020-07-05',
    address: '101 Maple Ave, Chicago, IL',
    bio: 'Michael is a seasoned product manager with experience in both startups and enterprise companies. He has successfully delivered multiple high-impact projects and is skilled in agile methodologies. Michael excels at translating business requirements into technical specifications.',
    education: [
      'MBA, University of Chicago, 2017',
      'B.S. Business Administration, Northwestern University, 2012',
    ],
    skills: ['Product Management', 'Agile', 'Scrum', 'JIRA', 'User Research', 'Roadmapping'],
    performance: 8.8,
    notes: 'Great at managing stakeholder expectations.',
    profileImage: 'https://randomuser.me/api/portraits/men/33.jpg',
  },
  {
    id: '5',
    name: 'Jessica Rodriguez',
    email: 'jessica.rodriguez@example.com',
    phone: '+1 (555) 567-8901',
    age: 26,
    class: 'Junior',
    attendance: 95.4,
    subjects: ['React', 'CSS', 'HTML'],
    department: 'Engineering',
    position: 'Frontend Developer',
    joinDate: '2023-05-15',
    address: '202 Elm St, Austin, TX',
    bio: 'Jessica is a talented frontend developer who joined the company recently. She has quickly adapted to our codebase and has already made significant contributions to the UI components library. Jessica is passionate about responsive design and accessibility.',
    education: [
      'B.S. Computer Science, UT Austin, 2022',
    ],
    skills: ['React', 'CSS', 'HTML', 'JavaScript', 'Responsive Design', 'Accessibility'],
    performance: 8.2,
    notes: 'Fast learner with great potential.',
    profileImage: 'https://randomuser.me/api/portraits/women/90.jpg',
  },
  {
    id: '6',
    name: 'James Smith',
    email: 'james.smith@example.com',
    phone: '+1 (555) 678-9012',
    age: 40,
    class: 'Senior',
    attendance: 99.1,
    subjects: ['Sales Strategy', 'Client Relations', 'CRM'],
    department: 'Sales',
    position: 'Sales Director',
    joinDate: '2019-02-10',
    address: '303 Cedar St, Seattle, WA',
    bio: 'James is an experienced sales director who has consistently exceeded targets. He has built strong relationships with key clients and has been instrumental in expanding our market presence. James is skilled at coaching his team and developing sales strategies.',
    education: [
      'B.A. Business, University of Washington, 2008',
    ],
    skills: ['Sales Strategy', 'Negotiation', 'CRM', 'Client Relations', 'Team Leadership'],
    performance: 9.5,
    notes: 'Outstanding performer and team leader.',
    profileImage: 'https://randomuser.me/api/portraits/men/54.jpg',
  },
  {
    id: '7',
    name: 'Olivia Taylor',
    email: 'olivia.taylor@example.com',
    phone: '+1 (555) 789-0123',
    age: 29,
    class: 'Mid-level',
    attendance: 94.8,
    subjects: ['Content Strategy', 'SEO', 'Social Media'],
    department: 'Marketing',
    position: 'Digital Marketing Specialist',
    joinDate: '2022-08-22',
    address: '404 Birch St, Portland, OR',
    bio: 'Olivia is a creative digital marketer with a strong understanding of SEO and content strategy. She has significantly improved our online presence and leads generation through targeted campaigns. Olivia stays up-to-date with the latest marketing trends.',
    education: [
      'B.A. Marketing, Portland State University, 2019',
    ],
    skills: ['Digital Marketing', 'SEO', 'Content Strategy', 'Social Media', 'Analytics', 'Email Marketing'],
    performance: 8.7,
    notes: 'Creative thinker with data-driven approach.',
    profileImage: 'https://randomuser.me/api/portraits/women/12.jpg',
  },
  {
    id: '8',
    name: 'Robert Garcia',
    email: 'robert.garcia@example.com',
    phone: '+1 (555) 890-1234',
    age: 33,
    class: 'Mid-level',
    attendance: 91.5,
    subjects: ['DevOps', 'AWS', 'CI/CD'],
    department: 'Engineering',
    position: 'DevOps Engineer',
    joinDate: '2021-11-15',
    address: '505 Walnut St, Denver, CO',
    bio: 'Robert is a skilled DevOps engineer who has improved our deployment processes and infrastructure reliability. He has implemented CI/CD pipelines and monitoring systems that have significantly reduced downtime. Robert is passionate about automation and security.',
    education: [
      'B.S. Information Technology, Colorado State University, 2015',
    ],
    skills: ['DevOps', 'AWS', 'Docker', 'Kubernetes', 'CI/CD', 'Terraform', 'Monitoring'],
    performance: 8.9,
    notes: 'Excellent at streamlining processes.',
    profileImage: 'https://randomuser.me/api/portraits/men/67.jpg',
  },
  {
    id: '9',
    name: 'Sophia Martinez',
    email: 'sophia.martinez@example.com',
    phone: '+1 (555) 901-2345',
    age: 31,
    class: 'Senior',
    attendance: 96.2,
    subjects: ['Data Analysis', 'Python', 'Machine Learning'],
    department: 'Data',
    position: 'Data Scientist',
    joinDate: '2020-10-05',
    address: '606 Spruce St, Miami, FL',
    bio: 'Sophia is a talented data scientist who has developed several predictive models that have helped optimize business decisions. She is skilled in Python and machine learning techniques. Sophia is currently working on customer behavior analysis to improve retention.',
    education: [
      'M.S. Data Science, University of Miami, 2019',
      'B.S. Statistics, Florida State University, 2016',
    ],
    skills: ['Python', 'R', 'Machine Learning', 'SQL', 'Data Visualization', 'Statistical Analysis'],
    performance: 9.1,
    notes: 'Exceptional analytical skills.',
    profileImage: 'https://randomuser.me/api/portraits/women/25.jpg',
  },
  {
    id: '10',
    name: 'Daniel Brown',
    email: 'daniel.brown@example.com',
    phone: '+1 (555) 012-3456',
    age: 27,
    class: 'Junior',
    attendance: 93.7,
    subjects: ['Mobile Development', 'Swift', 'iOS'],
    department: 'Engineering',
    position: 'iOS Developer',
    joinDate: '2023-03-10',
    address: '707 Cherry St, Atlanta, GA',
    bio: 'Daniel is a dedicated iOS developer who has contributed to several successful app releases. He is proficient in Swift and has a strong understanding of iOS design guidelines. Daniel is constantly learning new technologies to improve his skills.',
    education: [
      'B.S. Computer Science, Georgia Tech, 2021',
    ],
    skills: ['Swift', 'iOS', 'Xcode', 'UIKit', 'SwiftUI', 'Core Data', 'Git'],
    performance: 8.4,
    notes: 'Quick learner with passion for mobile development.',
    profileImage: 'https://randomuser.me/api/portraits/men/88.jpg',
  },
  {
    id: '11',
    name: 'Ava Wilson',
    email: 'ava.wilson@example.com',
    phone: '+1 (555) 123-4567',
    age: 34,
    class: 'Senior',
    attendance: 98.0,
    subjects: ['HR Management', 'Recruiting', 'Employee Relations'],
    department: 'HR',
    position: 'HR Manager',
    joinDate: '2019-08-15',
    address: '808 Aspen St, Philadelphia, PA',
    bio: 'Ava is an experienced HR manager who has implemented several initiatives to improve employee satisfaction and retention. She has streamlined our recruiting process and developed comprehensive onboarding programs. Ava is dedicated to fostering a positive company culture.',
    education: [
      'M.A. Human Resources, Temple University, 2015',
      'B.A. Psychology, University of Pennsylvania, 2012',
    ],
    skills: ['HR Management', 'Recruiting', 'Employee Relations', 'Onboarding', 'Performance Management', 'Benefits Administration'],
    performance: 9.3,
    notes: 'Exceptional people skills and strategic thinker.',
    profileImage: 'https://randomuser.me/api/portraits/women/55.jpg',
  },
  {
    id: '12',
    name: 'Ethan Harris',
    email: 'ethan.harris@example.com',
    phone: '+1 (555) 234-5678',
    age: 25,
    class: 'Intern',
    attendance: 97.5,
    subjects: ['QA', 'Testing', 'Automation'],
    department: 'Engineering',
    position: 'QA Engineer',
    joinDate: '2024-01-10',
    address: '909 Poplar St, Detroit, MI',
    bio: 'Ethan is a detail-oriented QA engineer who has identified numerous critical bugs before release. He has developed automated test scripts that have improved our testing efficiency. Ethan is passionate about ensuring high-quality software delivery.',
    education: [
      'B.S. Software Engineering, Michigan State University, 2023',
    ],
    skills: ['QA', 'Test Automation', 'Selenium', 'Cypress', 'Jest', 'Postman', 'JIRA'],
    performance: 8.0,
    notes: 'Meticulous attention to detail.',
    profileImage: 'https://randomuser.me/api/portraits/men/42.jpg',
  }
];